### ISSUE TITLE
PasteBin error

### ISSUE THREAD

**Issue by acid-0verride** [OniSensei/Discord-Reactions-to-CSV-Pastebin#1]
Hey!

so i was trying to export a list of reactions and i got a pastebin api error.  Is there a way to create private posts instead of public ones?
![image](https://user-images.githubusercontent.com/73712090/189240063-7359fb1f-4efd-4c3d-b25e-6c1000ad15aa.png)

Thank you!

**Comment by OniSensei** [comment]
There is currently not. However I can create a setting for this and update. Will keep you posted.

**Comment by OniSensei** [comment]
This has been fixed in the latest version which lets you select visibility of pastes in the settings.ini file.

[View Commit](https://github.com/OniSensei/Discord-Reactions-to-CSV-Pastebin/commit/7899602e94e91508ed3036728f4a09d7caf9c00d)
