### ISSUE TITLE
Support for custom emoji?

### ISSUE THREAD

**Issue by Darryldh** [OniSensei/Discord-Reactions-to-CSV-Pastebin#2]
Hi, The bot works well for the most part. Thanks!
It took me a long while to get running because it apparently does not work with custom emoji. It worked fine once I used a standard emoji like `:rofl:`.
Here is the error message that was produced
![image](https://user-images.githubusercontent.com/61126208/191320112-61738df5-109a-455b-ae04-1b7f9623bd90.png)

**Comment by OniSensei** [comment]
Unfortunately this is not something that the Discord library supports. I could possibly create a work around for this.  I will keep you posted.

**Comment by zautin1** [comment]
Did you ever create a work around for this? I also would like to use the program for events with custom emojis.

**Comment by OniSensei** [comment]
@zautin1 @Darryldh 

This has been fixed in the latest version which lets you add custom emotes in the settings.ini file.

[View Commit](https://github.com/OniSensei/Discord-Reactions-to-CSV-Pastebin/commit/7899602e94e91508ed3036728f4a09d7caf9c00d)
